/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day28_assingment;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        System.out.println("------------------------------------------------------------------");
        System.out.print("\t Login to Database   ");
        long millis = System.currentTimeMillis();
        java.util.Date date = new java.util.Date(millis);
        System.out.print(date);
        System.out.println(" \n ---------------------------------------------------------------");
        System.out.print("\t Enter the UserName : Default (postgres) ");
        String user_name = sc.next();
        System.out.print("\t Enter the Password :  ");
        String pass_word = sc.next();

        Student st = new Student();
        st.setId(46157);
        st.setName("testappl");
        StudImpl ob;
        ob = new StudImpl();
        do {

            System.out.println("------------------------------------------------------");
            System.out.println("\t\t Database Application Version 1.0   ");
            System.out.println("-------------------------------------------------------");
            System.out.println("\t\t  1.Insert Value  \n"
                    + "\t\t  2.Select Value \n"
                    + "\t\t  3.Update Value  \n"
                    + "\t\t  4.Delete Value  \n"
                    + "\t\t  5.Search Value  \n"
                    + "\t\t  6.Create table  \n"
                    + "\t\t  7.Exit ");

            System.out.print("\t  Enter Choice : ");
            int choice = sc.nextInt();

            if (choice == 1) {
                System.out.println("Enter id : ");
                int id1 = sc.nextInt();
                System.out.println("Enter name : ");
                String name1 = sc.next();
                Student st1 = new Student();
                st1.setId(id1);
                st1.setName(name1);
                ob.insert(st1);
            } else if (choice == 2) {
                ob.select(st);
            } else if (choice == 3) {
                System.out.println("Enter id : ");
                int id1 = sc.nextInt();
                System.out.println("Enter name : ");
                String name1 = sc.next();
                Student st1 = new Student();
                st1.setId(id1);
                st1.setName(name1);
                ob.update(st1);
            } else if (choice == 4) {
                System.out.println("Enter id : ");
                int id1 = sc.nextInt();
                Student st1 = new Student();
                st1.setId(id1);
                ob.delete(st1);
            } else if (choice == 5) {
                System.out.println("Enter id : ");
                int id1 = sc.nextInt();
                Student st1 = new Student();
                st1.setId(id1);
                ob.getStud(id1);
            } else if (choice == 6) {

                Student st1 = new Student();
                ob.create(st1);

            } else if (choice == 7) {
                System.out.println("Successfully logout !");
                System.exit(9);
            }
        } while (true);

    }
}
