/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javadao;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {

        Scanner sc = new Scanner(System.in);
        System.out.println("------------------------------------------------------------------");
        System.out.print("\t Login to Database   ");
        long millis = System.currentTimeMillis();
        java.util.Date date = new java.util.Date(millis);
        System.out.print(date);
        System.out.println(" \n ---------------------------------------------------------------");
        System.out.print("\t Enter the UserName : Default (postgres) ");
        String user_name = sc.next();
        System.out.print("\t Enter the Password :  ");
        String pass_word = sc.next();

        System.out.println("Enter id : ");
        int id = sc.nextInt();
        System.out.println("Enter name : ");
        String name = sc.next();

        Student st = new Student();
        st.setId(id);
        st.setName(name);

        StudentImple ob;
        ob = new StudentImple();

        ob.update(st);

        do {

            System.out.println("------------------------------------------------------");
            System.out.println("\t\t Database Application Version 1.0   ");
            System.out.println("-------------------------------------------------------");
            System.out.println("\t\t  1.Insert Value  \n"
                    + "\t\t  2.Create Value  \n"
                    + "\t\t  3.Select Value \n"
                    + "\t\t  4.Update Value  \n"
                    + "\t\t  5.Delete Value \n"
                    + "\t\t  6.Exit \n");

            System.out.print("\t  Enter Choice : ");
            int choice = sc.nextInt();

            if (choice == 1) {

            } else if (choice == 2) {
                System.out.println("2nd");

            } else if (choice == 3) {
                System.out.println("3rd");

            } else if (choice == 4) {
                System.out.println("4th");

            } else if (choice == 5) {
                System.out.println("5th");

            } else if (choice == 6) {

                // conn.close();
                System.out.println("\t\t Successfully Exit ! ");
                System.exit(0);
            }

        } while (true);

    }
}
